### ISSUE TITLE
Standalone WAM comparison between development and IPE_Refactor

### ISSUE THREAD

**Issue by twfang** [SWPC-IPE/WAM-IPE#258] opened 2018-11-26 20:12 UTC
This issue is to figure out weather or not the new Make system in IPE_refactor version change the solution in standalone WAM.

**Comment by twfang** [comment] 2018-11-28 20:34
I have carried out 10 day standalone WAM run for both development and IPE_refactor branches. The outputs are not bit-by-bit the same with different compilers. Most dramatic differences are located at around 100 km when I compare the Tn and mean mass. No significant changes is found in winds. I have outputs in netcdf format if you are interested in taking a look at them. 

![tn.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0595ab5bd71a00116dd1fe/125516c66e82c728ace21e0d46fc9ad86fc093bb80e3ba40b01faad67c4477267152a62a75d3e52aec462b515e0c1bf8415f594ceee59b69f7e8682fd70541b8937f5566c73a1badbd861cbb02bd218c4d84b7bf9801.png)
![mean_mass.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0595ab5bd71a00116dd1fe/125516c66e82c728ace21e0d46e5919b2dbd8ea89cfafd0fe64de29b234324676b5ee17e72d5b670e9477a0459091caf15585f45afacdd2ba1b03462964e49bc8f3900299f7744eeaa880dbe06b0218e4b86b2bf8d4dc7ee3e23e599c2.png)
![wind.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0595ab5bd71a00116dd1fe/125516c66e82c728ace21e0d46ff9d9427c0cfeb9ffbb049a15ee4d6730472717951fb7d7584e67eb94028055f5f4fff140c5f43faf19b37b4f46d2ede0356b49b381d66cc2f10a4b2831abb02be238c4e8db3bf824fd2a5.png)

**Comment by twfang** [comment] 2018-11-28 20:47
This is Tn at level 105 from these two runs. The differences are not obvious in the 2D plot. But the difference can be up to ~20% higher or lower at some places. 

![Tn_105.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0595ab5bd71a00116dd1fe/125516c66e82c728ace21e0d46dc9aa572d2d6ebc3abaf51ab57f5973d047d317c06f37e28d3e629ba147d035c0b4eac400b0a10fcfe8f23b4aa2e32db025fb28c341521842f1bbeb98515be04be238f4c82bfb88349c3ea2f68.png)

**Comment by timfullerrowell** [comment] 2018-11-28 21:02
Are these both before the radiation bug fix?

Is it just different compilers?

**Comment by twfang** [comment] 2018-11-28 21:09
These should be two identical codes but with different compilers.

**Comment by twfang** [comment] 2018-12-03 22:59
I have compared the 1st hour outputs between development and IPE_refactor branches. For all the plots I have shown above, there is no noticeable differences. Therefore, no plots is attached here. This suggests that the differences from the 10th-day results were grown with the model run time.

I will still do the test to compare the two branches using same compiling options.

**Comment by twfang** [comment] 2018-12-04 18:08
Three runs are compared here. 

1. Development branch (black line)
2. Development branch with compilers/configs from IPE_refactor branch (red line)
3. IPE_refactor branch (green line)

Results after 1-hr run, results from all three runs look identical:
![tn_1hr](https://user-images.githubusercontent.com/22968399/49462845-58c0bb80-f7b4-11e8-9ffb-ad527e5818f1.png)
![mean_mass_1hr](https://user-images.githubusercontent.com/22968399/49462855-5c544280-f7b4-11e8-9163-593dd887dd36.png)

Results after 10-day run, results from development branch deviate from other two runs since the compilers/config are different from other two runs. 
![tn_10day](https://user-images.githubusercontent.com/22968399/49462993-a806ec00-f7b4-11e8-9458-5699efdee8e0.png)
![mean_mass_10day](https://user-images.githubusercontent.com/22968399/49462995-aa694600-f7b4-11e8-8896-a4ef1fc42cc9.png)

Results here show that all three model results look identical in the figures after 1st hour. The codes are identical in these three runs. With the updated compilers/configs, differences can be found after a longer run.

**Comment by ZhuxiaoLi66** [comment] 2018-12-04 18:42
@twfang @joeschoonover good to know the results.  In theory, the output should bite by bite same. @twfang could you please confirm this after Theia back? Anyway, I think we confirmed the reason in the WAM physics change now. Since the refactor-IPE is not ready yet (not urgent to get the new configuration in) , I would like to do a long term run and more 2D plots to estimate the influence of the new compile options on WAM physics later.

**Comment by joeschoonover** [comment] 2018-12-04 18:51
@ZhuxiaoLi66 could you open an issue to do this sort of investigation?

 A path forward on this matter, that I see would make everyone reasonably happy, is to bring in the change of compilers/config into development. This issue has documented fairly well, that there are minor impacts to large scale atmospheric fields. After merging these changes into development, we can tag that version to allow us to easily go back and investigate, in detail, the impacts of these changes.

**Comment by twfang** [comment] 2018-12-05 15:23
I have compare files from standalone WAM runs from development+refactor compilers/config and IPE_refactor. Results are bit-by-bit identical for all the outputs (i.e., from the first hour to 10-day output). I am comfortable with the compiler changes now.

**Comment by ZhuxiaoLi66** [comment] 2018-12-05 16:05
@twfang Good to know, thank you.

**Comment by ZhuxiaoLi66** [comment] 2018-12-08 16:20
@joeschoonover thanks for the thoughts. I open a new issue #264 just now. Let us do the validation at first, it is another good practice for the routinely validation for WAM in near the future, especially it seems no obvious reason for us to be rushed on this for now.

**Comment by joeschoonover** [comment] 2018-12-10 16:06
Good idea. In favor of continuing work on #264, can we close this issue ?

**Closed** 2018-12-10 19:51 UTC
Labels: in progress
