### ISSUE TITLE
Test and resolve any issues with coupled WAM-IPE (refactored)

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#288] opened 2019-03-27 18:34 UTC

**Comment by joeschoonover** [comment] 2019-04-04 00:49
When executing with submit.sh and the march2013_regression.config file on the ipe_refactor branch, the the job is submitted, files are setup in stmp3 and stmp4 directories as expected.

The fcst file has a ton of output showing environment variables that are set and files that are moved around.
 The last statement seen in the fcst file, before the job is terminated by the job scheduler, is 
```
++ [[ 90 -gt 150 ]]
++ cat
++ /bin/ln -sf atm_namelist.rc ./model_configure
++ '[' NO = YES ']'
++ eval '$FCST_LAUNCHER' '$DATA/$(basename' '$FCSTEXEC)' '1>&1' '2>&2'
++++ basename /scratch3/NCEPDEV/swpc/noscrub/Joseph.Schoonover/demo/WAM-IPE/scripts/compsets/../../NEMS/exe/NEMS.x
+++ /apps/intel/impi/5.1.2.150/intel64/bin/mpirun /scratch4/NCEPDEV/stmp4/Joseph.Schoonover/refactored_wam-ipe/NEMS.x
```

Notice that the number of mpi ranks is not set in the mpirun call - it looks like `scripts/compsets/config/compute.config` is responsible for this one.. particularly [line 23 ](https://github.com/SWPC-IPE/WAM-IPE/blob/ipe_refactor/scripts/compsets/config/compute.config#L23)

When I uncommented this line, the last line in the fcst file is now
```
++ eval '$FCST_LAUNCHER' '$DATA/$(basename' '$FCSTEXEC)' '1>&1' '2>&2'
++++ basename /scratch3/NCEPDEV/swpc/noscrub/Joseph.Schoonover/demo/WAM-IPE/scripts/compsets/../../NEMS/exe/NEMS.x
+++ /apps/intel/impi/5.1.2.150/intel64/bin/mpirun -np 60 /scratch4/NCEPDEV/stmp4/Joseph.Schoonover/refactored_wam-ipe/NEMS.x
```
which is what it should be. However, the code just hangs and no further output is sent to screen. Because the execution of this code is so buried underneath "script lasagna", it's a huge effort to just run the code under a profiler or debugger. 

@akubaryk maybe you have some insight into what may be going on or what to look into ?

**Comment by akubaryk** [comment] 2019-04-04 01:30
The result should be the same either way -- mpirun when not invoked with `-np XX` defaults to the number of processors available according to the scheduler's environment variables, which is why it was coded that way.

I'm not sure what you mean by the last paragraph; it's a necessity that a substantial amount of setup is done for each forecast execution. Of course you can remove the `set -ax` or `set -x` if you don't want to see it. Is it not possible to attach the debugger only to the mpirun instance? In which case you want to set FCST_LAUNCHER in march2013_regression.config appropriately.

The NEMS.x should be outputting PET00.ESMF_LogFile (up to however many processors you have designated) -- if it's not, I'm going to suggest it's an issue with your environment, because I just did this:
```
cp -r /scratch3/NCEPDEV/swpc/noscrub/Joseph.Schoonover/demo/WAM-IPE /scratch3/NCEPDEV/swpc/save/Adam.Kubaryk/WAM-IPE/joe_refactor
cd !$/scripts/compsets
./submit.sh march2013_regression.config
```
and you'll find running output here: /scratch4/NCEPDEV/stmp3/Adam.Kubaryk/refactored_wam-ipe

**Comment by joeschoonover** [comment] 2019-04-04 16:42
I'm not seeing any PET*.ESMF_LogFile in the stmp4 directory. What environment settings are related to ESMF that could cause this ?

**Comment by akubaryk** [comment] 2019-04-04 16:56
ESMF only looks at print_esmf in model_configure, and it'll always be set to .true. by the run scripts unless you have pre-set it to something else in your environment. However, if you're also not getting model output, that means that there's something interfering with the `mpirun NEMS.x` command in your environment -- can you run the development branch of WAM-IPE without issue? I feel like, given that I copied your files straight over and ran without issue, that this might be something to take up with RDHPCS support?

**Comment by joeschoonover** [comment] 2019-04-04 19:07
I can't run the development branch either. Just submitted a ticket to RDHPCS support.

**Comment by joeschoonover** [comment] 2019-04-05 15:20
Response from RDHPCS
```
Since your colleagues are able to run the script. I suspect this is an issue with your environment. I glanced at the script and there are several environment variables that need to be set for the script to execute correctly. I see there is a config directory inside the compsets directory that contains several configuration files. You probably need to source one or more of those (e.g. there is a "theia.config") in order to properly set up your environment.
```

**Comment by akubaryk** [comment] 2019-04-05 15:34
That is not a good response from them, the machine config files are sourced... the job wouldn't even submit if it wasn't.

**Comment by joeschoonover** [comment] 2019-04-05 15:41
Working towards a minimal reproducer.

**Comment by joeschoonover** [comment] 2019-04-05 21:11
I've gotten it resolved and the code is running - the issue was an ssh key not being added to my authorized key file.
Now onto actually assessing the coupled code.

**Comment by akubaryk** [comment] 2019-07-17 21:18
closing this in favor of individual issues as they pop up with the `ipe_refactor_*` branches.

**Closed by akubaryk** 2019-07-17 21:18 UTC
