### ISSUE TITLE
New 2d decomp -- growing errors after several hours of integration

### ISSUE THREAD

**Issue by akubaryk** [SWPC-IPE/WAM-IPE#35] opened 2017-10-04 19:07 UTC
The new 2d decomposition produces bitwise identical results for 1x80 and 10x8, but not 8x10. Taking an ncdiff between two files after 24 hours of integration shows differences along a single domain edge (?) on the order of 10^-11 (e.g. NmF2 error of O(10^1) with NmF2 values O(10^12)). These persist and grow to 10^-7 through ~4.5 days of integration, but do not appear along any other domain edge.

Below you can see images from ~4.5 days of integration; note the highly meridional structure. Taking the set of non-zero points from the ncdiff'd He+ field gives the following list of unique (l,m): `/scratch3/NCEPDEV/swpc/noscrub/Adam.Kubaryk/decomp_comparison/new_diff/output`, made from `/scratch3/NCEPDEV/swpc/noscrub/Adam.Kubaryk/decomp_comparison/new_diff/lpmpize.py`. They are mostly concentrated along m=41. Some debug height-regridding code gives an approximate (l,m) for each regridded point; that code is in the experimental `debug-mp-lp-regrid` branch.

NmF2 diff 1x80-8x10
![nmf2_diff_1x80-8x10](https://user-images.githubusercontent.com/31134616/31193666-c99fe50c-a912-11e7-92b7-1f9e3d668b44.png)

He+ diff 1x80-8x10 @ 470km
![he _diff_1x80-8x10_470km](https://user-images.githubusercontent.com/31134616/31193664-c99caee6-a912-11e7-84de-14dff9117f42.png)

Same @ 580km
![he _diff_1x80-8x10_580km](https://user-images.githubusercontent.com/31134616/31193665-c99ed78e-a912-11e7-8e50-d75981041db3.png)

**Comment by joeschoonover** [comment] 2017-10-19 17:33
IPE Standalone runs with 1x80, 2x40, 4x20, and 8x10 domain decompositions produce identical results (to machine precision) to the MS0.6 run with 1x80.

**Comment by akubaryk** [comment] 2017-10-19 17:56
Raffaele suggested the compiler option `-fp-model strict`. It slows down IPE but produces identical results for 1x80, 4x20, 8x10, and 10x8. 2x40 was not bitwise identical, but after post-processing (IPE height regridding), the resulting NetCDF output files were identical.

**Comment by joeschoonover** [comment] 2017-10-24 19:24
Test runs with different domain decompositions with and without coupling are summarized here : 
https://docs.google.com/spreadsheets/d/1aoTV2T14ROjNte7mJv55Xtho2RTCnl8VZiJplqMhFtY/edit?usp=sharing

**Comment by joeschoonover** [comment] 2017-10-25 17:46
This issue is marked as completed, since we have documented clearly the decompositions of IPE and WAM-IPE that are functional. This issue however, will remain open.

**Comment by joeschoonover** [comment] 2017-10-31 21:06
Summary from @rmontuoro  in an email : 
" 
After a WAM-IPE development branch (ipe_nuopc_2d_petlayout) including a new version of the NUOPC cap for the IPE model component was merged ( 2c146c8b6e1bc4a95d25c8ef576d0ebba2f10e93 ) with the main WAM-IPE development branch, it was discovered that the resulting code crashed after 1 hour of running on both a cold start and restart. Issue #32 was opened on the WAM-IPE GitHub repository on September 22 to document work related to this problem.

The source of this issue was traced back to the 2d plasma grid array not being properly distributed among ranks. Changes were introduced in the IPE cap to address it on October 4 (commit: https://github.com/SWPC-IPE/WAM-IPE/commit/96c84abbf0a70818ce51766a68e91e0758cd0769). 
Preliminary but extensive tests showed that these changes corrected the problem and issue #32 was closed on October 5.

Further tests were performed with WAM-IPE in order to thoroughly evaluate the capability of the new IPE cap to run with generic 2D decompositions. Those tests consisted of 5-day, 1-way coupled simulations starting on 03/16/2013 (based on provided compset: swpc%20130316_5day_spacewx_gsm%wam%T62_ipe%80x170) using the following (l,m) decompositions for IPE: 1x80, 2x40, 4x20, 8x10, 10x8, 20x4, 40x2, and 80x1. To minimize potential interference from aggressive code optimization in IPE (-O3), the compiler option: "-fp-model strict" was added to ensure reproducibility of floating point operations. Also, standalone IPE simulations were performed to provide an additional baseline.
The results of those tests are reported in the shared spreadsheet: https://docs.google.com/spreadsheets/d/1aoTV2T14ROjNte7mJv55Xtho2RTCnl8VZiJplqMhFtY/edit#gid=0.

To summarize, all simulations ran successfully with the exception of decompositions 40x2 and 80x1, which crashed due to the SMS preprocessor being unable to setup the requested (l,m) decomposition. The error reported was: 
ASSERTION Error in line         1511  of file ppp_module.F90

Simulation runtime of working decompositions other than 1x80 was higher than 1x80. Neutral output was bitwise identical among all working decompositions for all of the available time steps. Plasma output was also identical except for 4x20 case, where it started to show differences in individual ion fields at time step 201303191630 (about 3.7 days into the simulation). Issue #35 was opened to track these validation tests  and marked completed on October 25. At this point there is no evidence that the new IPE cap is responsible for the observed differences in the 4x20 plasma output.

During testing, the following bugs were also discovered and corrected:

1. A missing comma caused a few variables to be undeclared in IPELIB/src/eldyn/module_sunloc.f.
3f6bcb727bad2580c3ad2db6d166c723ef4453d1

2. The SMS preprocessor was handling incorrectly an IF statement in IPELIB/src/plasma/module_sub_plasma.f90. As a result, the code was accessing unallocated memory. IF statement replaced with IF/THEN block. 5f2216b578faf7927c5b3bed41a238040d3d3734

Minor additional changes to the new IPE cap were also applied to the head of development branch to properly log errors from deallocate statements and improve MPI synchronization during halo exchange ( 
fb8987965ecefeb806d66de4e07814721a2c9d16 ). 

The resulting code was merged with the raw_high_lat branch on October 24. An initial WAM-IPE simulation using the 58x8 decomposition completed successfully (Joe Schoonover). Results are awaiting scientific validation. "

**Comment by joeschoonover** [comment] 2017-11-06 18:33
With this summary, I'm going to close this issue, with the understanding that certain domain decompositions don't work.

**Closed by joeschoonover** 2017-11-06 18:33 UTC
Labels: confirmed, low priority
